name: deploy

# 当代码提交到 main 分支时触发 GitHub Actions
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout源码
        uses: actions/checkout@v4
        with:
          submodules: true  # 自动拉取可能存在的主题子模块
          fetch-depth: 0

      - name: 安装最新版 Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: 编译静态网页
        run: hugo --gc --minify

      - name: 自动部署到 gh-pages 分支
        uses: peaceiris/actions-gh-pages@v4
        with:
          PERSONAL_TOKEN: ${{ secrets.GH_PAT }} # 对应我们刚才锁进仓库的密钥名字
          PUBLISH_BRANCH: gh-pages              # 极其关键！网页发布到独立的 gh-pages 分支，绝不污染 main 源码
          PUBLISH_DIR: ./public                 # 编译生成的静态文件夹
          commit_message: "🤖 姐姐的魔力自动部署: ${{ github.event.head_commit.message }}"